/**:
  controller_manager:
    ros__parameters:

      robotiq_gripper_hande_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController

  robotiq_gripper_hande_controller:
    ros__parameters:
      default: true
      joints: 
        - $(var tf_prefix)finger_1_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
  robotiq_activation_controller:
    ros__parameters:
      default: true
