/**:
  controller_manager:
    ros__parameters:

    robotiq_gripper_hande_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

robotiq_gripper_hande_controller:
  ros__parameters:
    joints:
      - finger_1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0

  # robotiq_gripper_hande_controller:
  #   ros__parameters:
  #     default: true
  #     joint: $(var tf_prefix)finger_1_joint

  robotiq_activation_controller:
    ros__parameters:
      default: true
